//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bug
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="*Field is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "*Project is required")]
        public string Project { get; set; }


        [Required(ErrorMessage = "*Field is required")]
        public string Type { get; set; }

        [Required(ErrorMessage = "*Assignee is required")]
        public string Assignee { get; set; }

        [Required(ErrorMessage = "*BugStatus is required")]
        public string BugStatus { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [Required(ErrorMessage ="*Give a brief Description")]
        public string Description { get; set; }
    }
}
