//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Project
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "*Field is required")]
        public string ProjectTitle { get; set; }

        [Required(ErrorMessage = "*Field is required")]
        public string Type { get; set; }

        [Required(ErrorMessage = "*Manager is required")]
        public string Manager { get; set; }

        [Required(ErrorMessage = "*Frontend is required")]
        public string Frontend { get; set; }

        [Required(ErrorMessage = "*Backend is required")]
        public string Backend { get; set; }

        [Required(ErrorMessage = "*ClientName is required")]
        public string ClientName { get; set; }

        [Required(ErrorMessage = "*Description is required")]
        public string Description { get; set; }
    }
}
