//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Net.Http;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "*Field is required")]
        public string TicketId { get; set; }

        [Required(ErrorMessage = "*Field is required")]
        public string Ticket_Title { get; set; }

        [Required(ErrorMessage = "*Ticket_Description is required")]
        public string Ticket_Description { get; set; }

        [Required(ErrorMessage = "*Assignee is required")]
        public string Assigned_Developer { get; set; }

        [Required(ErrorMessage = "*Submitter is required")]
        public string Submitter { get; set; }

        [Required(ErrorMessage = "*Project is required")]
        public string Project { get; set; }

        [Required(ErrorMessage = "*Priority is required")]
        public string Ticket_Priority { get; set; }

        [Required(ErrorMessage = "*Status is required")]
        public string Ticket_Status { get; set; }

        [Required(ErrorMessage = "*Type is required")]
        public string Ticket_Type { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Created { get; set; }

    }
}
